###
POST http://localhost:8080/test/getLog
Content-Type: application/json

{
  "day": "2023-08-28",
  "ips": ["192.168.21.123"],
  "level": "error-log.log",
  "rows": 5000,
  "server": "VIP",
  "showIp": true
}